var sportsbook = {
"type": "FeatureCollection",
"name": "sportsbook",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "name": "Arkansas", "location": "Oaklawn Racing Casino Resort" }, "geometry": { "type": "Point", "coordinates": [ -93.05909, 34.48405 ] } },
{ "type": "Feature", "properties": { "name": "Arkansas", "location": "Southland Park Gamin and Racing" }, "geometry": { "type": "Point", "coordinates": [ -90.15961, 35.16188 ] } },
{ "type": "Feature", "properties": { "name": "Delaware", "location": "Dover Downs Hotel & Casino" }, "geometry": { "type": "Point", "coordinates": [ -75.53254, 39.18838 ] } },
{ "type": "Feature", "properties": { "name": "Delaware", "location": "Harrington Raceway & Casino" }, "geometry": { "type": "Point", "coordinates": [ -75.57614, 38.91348 ] } },
{ "type": "Feature", "properties": { "name": "Delaware", "location": "Delaware Park Racetrack" }, "geometry": { "type": "Point", "coordinates": [ -75.65512, 39.70934 ] } },
{ "type": "Feature", "properties": { "name": "District Of Columbia", "location": "William Hill Sportsbook at Capital One Arena" }, "geometry": { "type": "Point", "coordinates": [ -77.02092, 38.89813 ] } },
{ "type": "Feature", "properties": { "name": "Colorado", "location": "Wildwood Casino" }, "geometry": { "type": "Point", "coordinates": [ -105.17356, 38.75031 ] } },
{ "type": "Feature", "properties": { "name": "Colorado", "location": "Bronco Billy's Casino" }, "geometry": { "type": "Point", "coordinates": [ -105.17748, 38.74682 ] } },
{ "type": "Feature", "properties": { "name": "Colorado", "location": "Ameristar Casino Resort Spa" }, "geometry": { "type": "Point", "coordinates": [ -105.48916, 39.79995 ] } },
{ "type": "Feature", "properties": { "name": "Colorado", "location": "Isle Casino Hotel" }, "geometry": { "type": "Point", "coordinates": [ -105.48365, 39.79813 ] } },
{ "type": "Feature", "properties": { "name": "Colorado", "location": "Saratoga Casino" }, "geometry": { "type": "Point", "coordinates": [ -105.494, 39.80125 ] } },
{ "type": "Feature", "properties": { "name": "Illinois", "location": "Rivers Casino" }, "geometry": { "type": "Point", "coordinates": [ -87.86423, 41.99755 ] } },
{ "type": "Feature", "properties": { "name": "Illinois", "location": "The Sportsbook at Hollywood Casino" }, "geometry": { "type": "Point", "coordinates": [ -88.31344, 41.75935 ] } },
{ "type": "Feature", "properties": { "name": "Illinois", "location": "Casino Queen" }, "geometry": { "type": "Point", "coordinates": [ -90.17415, 38.62587 ] } },
{ "type": "Feature", "properties": { "name": "Illinois", "location": "Hollywood Casino & Hotel" }, "geometry": { "type": "Point", "coordinates": [ -88.14531, 41.47928 ] } },
{ "type": "Feature", "properties": { "name": "Illinois", "location": "Grand Victoria Casino" }, "geometry": { "type": "Point", "coordinates": [ -88.27962, 42.03142 ] } },
{ "type": "Feature", "properties": { "name": "Indiana", "location": "Horshoe Hammond Casino" }, "geometry": { "type": "Point", "coordinates": [ -87.50584, 41.69423 ] } },
{ "type": "Feature", "properties": { "name": "Indiana", "location": "Indiana Grand Racing and Casino" }, "geometry": { "type": "Point", "coordinates": [ -85.82449, 39.58919 ] } },
{ "type": "Feature", "properties": { "name": "Indiana", "location": "Belterra Casino Resort" }, "geometry": { "type": "Point", "coordinates": [ -84.93932, 38.78013 ] } },
{ "type": "Feature", "properties": { "name": "Indiana", "location": "French Lick Resort" }, "geometry": { "type": "Point", "coordinates": [ -86.61908, 38.55418 ] } },
{ "type": "Feature", "properties": { "name": "Indiana", "location": "Blue Chip Casino Hotel Spa" }, "geometry": { "type": "Point", "coordinates": [ -86.89298, 41.71868 ] } },
{ "type": "Feature", "properties": { "name": "Indiana", "location": "Rising Star Casino Resort" }, "geometry": { "type": "Point", "coordinates": [ -84.8465, 38.95271 ] } },
{ "type": "Feature", "properties": { "name": "Iowa", "location": "Diamond Jo Worth Casino" }, "geometry": { "type": "Point", "coordinates": [ -93.352, 43.44764 ] } },
{ "type": "Feature", "properties": { "name": "Iowa", "location": "Isle Casino Hotel" }, "geometry": { "type": "Point", "coordinates": [ -90.50674, 41.52371 ] } },
{ "type": "Feature", "properties": { "name": "Iowa", "location": "Catfish Bend Casino" }, "geometry": { "type": "Point", "coordinates": [ -91.13917, 40.82327 ] } },
{ "type": "Feature", "properties": { "name": "Iowa", "location": "Grand Falls Casino & Golf Resort" }, "geometry": { "type": "Point", "coordinates": [ -96.50329, 43.49845 ] } },
{ "type": "Feature", "properties": { "name": "Iowa", "location": "Rhythm City Casino Resort" }, "geometry": { "type": "Point", "coordinates": [ -90.53041, 41.59489 ] } },
{ "type": "Feature", "properties": { "name": "Iowa", "location": "Wild Rose Casino Resort" }, "geometry": { "type": "Point", "coordinates": [ -94.66179, 43.11503 ] } },
{ "type": "Feature", "properties": { "name": "Iowa", "location": "Hard Rock Hotel & Casino" }, "geometry": { "type": "Point", "coordinates": [ -96.40881, 42.49372 ] } },
{ "type": "Feature", "properties": { "name": "Michigan", "location": "FireKeepers Casino Hotel" }, "geometry": { "type": "Point", "coordinates": [ -85.07507, 42.29692 ] } },
{ "type": "Feature", "properties": { "name": "Michigan", "location": "Four Winds Casino" }, "geometry": { "type": "Point", "coordinates": [ -86.1625, 41.94576 ] } },
{ "type": "Feature", "properties": { "name": "Michigan", "location": "Little River Casino Resort" }, "geometry": { "type": "Point", "coordinates": [ -86.24607, 44.28598 ] } },
{ "type": "Feature", "properties": { "name": "Michigan", "location": "Turtle Creek Casino & Hotel" }, "geometry": { "type": "Point", "coordinates": [ -85.42173, 44.77408 ] } },
{ "type": "Feature", "properties": { "name": "Michigan", "location": "MotorCity Casino Hotel" }, "geometry": { "type": "Point", "coordinates": [ -83.06973, 42.33898 ] } },
{ "type": "Feature", "properties": { "name": "Mississippi", "location": "Beau Rivage Resort & Casino" }, "geometry": { "type": "Point", "coordinates": [ -88.8915, 30.39231 ] } },
{ "type": "Feature", "properties": { "name": "Mississippi", "location": "Water View Casino & Hotel" }, "geometry": { "type": "Point", "coordinates": [ -90.89677, 32.32423 ] } },
{ "type": "Feature", "properties": { "name": "Mississippi", "location": "Bok Homa Casino" }, "geometry": { "type": "Point", "coordinates": [ -89.00876, 31.77776 ] } },
{ "type": "Feature", "properties": { "name": "Mississippi", "location": "Riverwalk Casino Hotel" }, "geometry": { "type": "Point", "coordinates": [ -90.91364, 32.29796 ] } },
{ "type": "Feature", "properties": { "name": "Mississippi", "location": "Golden Moon Hotel & Casino" }, "geometry": { "type": "Point", "coordinates": [ -89.20393, 32.774 ] } },
{ "type": "Feature", "properties": { "name": "Mississippi", "location": "Magnolia Bluffs Casino" }, "geometry": { "type": "Point", "coordinates": [ -91.4051, 31.5657 ] } },
{ "type": "Feature", "properties": { "name": "Mississippi", "location": "Sam's Town Hotel and Gambling Hall" }, "geometry": { "type": "Point", "coordinates": [ -90.41178, 34.81912 ] } },
{ "type": "Feature", "properties": { "name": "Mississippi", "location": "Island View Casino Resort" }, "geometry": { "type": "Point", "coordinates": [ -89.10322, 30.3636 ] } },
{ "type": "Feature", "properties": { "name": "Montana", "location": "Happy Endings Casino" }, "geometry": { "type": "Point", "coordinates": [ -112.93239, 46.12709 ] } },
{ "type": "Feature", "properties": { "name": "Montana", "location": "Lucky Buckys Casino" }, "geometry": { "type": "Point", "coordinates": [ -111.96409, 46.59078 ] } },
{ "type": "Feature", "properties": { "name": "Montana", "location": "Jack Rabbit Reds Casino" }, "geometry": { "type": "Point", "coordinates": [ -111.18611, 45.76527 ] } },
{ "type": "Feature", "properties": { "name": "Montana", "location": "Montana Nugget Casino" }, "geometry": { "type": "Point", "coordinates": [ -114.32639, 48.20009 ] } },
{ "type": "Feature", "properties": { "name": "Montana", "location": "Treasure Creek Casino" }, "geometry": { "type": "Point", "coordinates": [ -108.58421, 45.77139 ] } },
{ "type": "Feature", "properties": { "name": "Montana", "location": "Papa Rays Casino" }, "geometry": { "type": "Point", "coordinates": [ -111.94204, 46.53983 ] } },
{ "type": "Feature", "properties": { "name": "Montana", "location": "Knotty Casino" }, "geometry": { "type": "Point", "coordinates": [ -109.24669, 45.18627 ] } },
{ "type": "Feature", "properties": { "name": "Montana", "location": "Lucky Lil's Casino" }, "geometry": { "type": "Point", "coordinates": [ -112.53945, 46.00717 ] } },
{ "type": "Feature", "properties": { "name": "Nevada", "location": "Eldorado Casino" }, "geometry": { "type": "Point", "coordinates": [ -114.98354, 36.03195 ] } },
{ "type": "Feature", "properties": { "name": "Nevada", "location": "Wynn Las Vegas" }, "geometry": { "type": "Point", "coordinates": [ -115.16576, 36.12654 ] } },
{ "type": "Feature", "properties": { "name": "Nevada", "location": "Jokers Wild Casino" }, "geometry": { "type": "Point", "coordinates": [ -114.9946, 36.05195 ] } },
{ "type": "Feature", "properties": { "name": "Nevada", "location": "The Cromwell Hotel and Casino" }, "geometry": { "type": "Point", "coordinates": [ -115.17181, 36.11503 ] } },
{ "type": "Feature", "properties": { "name": "Nevada", "location": "Aliante Casino Hotel Spa" }, "geometry": { "type": "Point", "coordinates": [ -115.18012, 36.29253 ] } },
{ "type": "Feature", "properties": { "name": "Nevada", "location": "Caesars Palace" }, "geometry": { "type": "Point", "coordinates": [ -115.17449, 36.11613 ] } },
{ "type": "Feature", "properties": { "name": "Nevada", "location": "Harrah's Lake Tahoe" }, "geometry": { "type": "Point", "coordinates": [ -119.94129, 38.95923 ] } },
{ "type": "Feature", "properties": { "name": "Nevada", "location": "Luxor" }, "geometry": { "type": "Point", "coordinates": [ -115.17669, 36.09571 ] } },
{ "type": "Feature", "properties": { "name": "Nevada", "location": "Harveys Lake Tahoe" }, "geometry": { "type": "Point", "coordinates": [ -119.9427, 38.96018 ] } },
{ "type": "Feature", "properties": { "name": "Nevada", "location": "The Mirage" }, "geometry": { "type": "Point", "coordinates": [ -115.17402, 36.12137 ] } },
{ "type": "Feature", "properties": { "name": "Nevada", "location": "Fremont Hotel and Casino" }, "geometry": { "type": "Point", "coordinates": [ -115.14341, 36.17112 ] } },
{ "type": "Feature", "properties": { "name": "Nevada", "location": "Palms Casino Resort" }, "geometry": { "type": "Point", "coordinates": [ -115.19501, 36.11486 ] } },
{ "type": "Feature", "properties": { "name": "Nevada", "location": "Excalibur" }, "geometry": { "type": "Point", "coordinates": [ -115.1761, 36.09883 ] } },
{ "type": "Feature", "properties": { "name": "Nevada", "location": "Cannery Casino" }, "geometry": { "type": "Point", "coordinates": [ -115.11893, 36.23837 ] } },
{ "type": "Feature", "properties": { "name": "Nevada", "location": "Harrah's Reno" }, "geometry": { "type": "Point", "coordinates": [ -119.81253, 39.52771 ] } },
{ "type": "Feature", "properties": { "name": "New Jersey", "location": "Borgata Hotel Casino Spa" }, "geometry": { "type": "Point", "coordinates": [ -74.43568, 39.37739 ] } },
{ "type": "Feature", "properties": { "name": "New Jersey", "location": "Hard Rock Hotel & Casino" }, "geometry": { "type": "Point", "coordinates": [ -74.42044, 39.36013 ] } },
{ "type": "Feature", "properties": { "name": "New Jersey", "location": "Meadowlands Racing and Entertainment" }, "geometry": { "type": "Point", "coordinates": [ -74.07168, 40.8201 ] } },
{ "type": "Feature", "properties": { "name": "New Jersey", "location": "Golden Nugget Atlantic City" }, "geometry": { "type": "Point", "coordinates": [ -74.42786, 39.37963 ] } },
{ "type": "Feature", "properties": { "name": "New Mexico", "location": "Santa Ana Star Casino Hotel" }, "geometry": { "type": "Point", "coordinates": [ -106.56509, 35.32832 ] } },
{ "type": "Feature", "properties": { "name": "New Mexico", "location": "Hilton Buffalo Thunder Resort and Casino" }, "geometry": { "type": "Point", "coordinates": [ -105.99592, 35.861 ] } },
{ "type": "Feature", "properties": { "name": "New Mexico", "location": "Isleta Resort and Casino" }, "geometry": { "type": "Point", "coordinates": [ -106.66183, 34.93769 ] } },
{ "type": "Feature", "properties": { "name": "New York", "location": "Rivers Casino and Resort" }, "geometry": { "type": "Point", "coordinates": [ -73.93594, 42.82353 ] } },
{ "type": "Feature", "properties": { "name": "New York", "location": "Tioga Downs Casino Resort" }, "geometry": { "type": "Point", "coordinates": [ -76.41306, 42.02389 ] } },
{ "type": "Feature", "properties": { "name": "New York", "location": "Seneca Buffalo Creek Casino" }, "geometry": { "type": "Point", "coordinates": [ -78.87008, 42.87357 ] } },
{ "type": "Feature", "properties": { "name": "New York", "location": "Point Palace Casino" }, "geometry": { "type": "Point", "coordinates": [ -75.96543, 43.15487 ] } },
{ "type": "Feature", "properties": { "name": "Pennsylvania", "location": "Mohegan Sun Pocono" }, "geometry": { "type": "Point", "coordinates": [ -75.822, 41.26946 ] } },
{ "type": "Feature", "properties": { "name": "Pennsylvania", "location": "Valley Forge Casino Resort" }, "geometry": { "type": "Point", "coordinates": [ -75.41584, 40.09674 ] } },
{ "type": "Feature", "properties": { "name": "Pennsylvania", "location": "Rivers Casino" }, "geometry": { "type": "Point", "coordinates": [ -80.02217, 40.44664 ] } },
{ "type": "Feature", "properties": { "name": "Pennsylvania", "location": "Harrah's Philadelphia" }, "geometry": { "type": "Point", "coordinates": [ -75.34835, 39.85089 ] } },
{ "type": "Feature", "properties": { "name": "Pennsylvania", "location": "Presque Isle Downs and Casino" }, "geometry": { "type": "Point", "coordinates": [ -80.03094, 42.06851 ] } },
{ "type": "Feature", "properties": { "name": "Rhode Island", "location": "Tiverton Casino Hotel" }, "geometry": { "type": "Point", "coordinates": [ -71.15873, 41.66208 ] } },
{ "type": "Feature", "properties": { "name": "West Virginia", "location": "Hollywood Casino at Charles Town Races" }, "geometry": { "type": "Point", "coordinates": [ -77.8522, 39.29712 ] } },
{ "type": "Feature", "properties": { "name": "West Virginia", "location": "Wheeling Island Hotel Casino Racetrack" }, "geometry": { "type": "Point", "coordinates": [ -80.73229, 40.06271 ] } },
{ "type": "Feature", "properties": { "name": "West Virginia", "location": "Mardi Gras Casino and Resort" }, "geometry": { "type": "Point", "coordinates": [ -81.81057, 38.42075 ] } },
{ "type": "Feature", "properties": { "name": "West Virginia", "location": "The Casino Club at the Greenbrier" }, "geometry": { "type": "Point", "coordinates": [ -80.3082, 37.7863 ] } }
]
}
