var states_legal_no_points = {
"type": "FeatureCollection",
"name": "states_legal_no_points",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Alaska", "Status": "Failed legislation in 2020", "Wagers": "No data", "Casinos": "No data", "Rules": "No data", "Total_Hand": "No data", "Sportsbook": "No data", "State_Taxe": "No data" }, "geometry": { "type": "Point", "coordinates": [ -152.58867, 64.29455 ] } },
{ "type": "Feature", "properties": { "Name": "Alabama", "Status": "Failed legislation in 2020", "Wagers": "No data", "Casinos": "No data", "Rules": "No data", "Total_Hand": "No data", "Sportsbook": "No data", "State_Taxe": "No data" }, "geometry": { "type": "Point", "coordinates": [ -86.83148, 32.79387 ] } },
{ "type": "Feature", "properties": { "Name": "Arizona", "Status": "Failed legislation in 2020", "Wagers": "No data", "Casinos": "No data", "Rules": "No data", "Total_Hand": "No data", "Sportsbook": "No data", "State_Taxe": "No data" }, "geometry": { "type": "Point", "coordinates": [ -111.66017, 34.29158 ] } },
{ "type": "Feature", "properties": { "Name": "California", "Status": "Failed legislation in 2020", "Wagers": "No data", "Casinos": "No data", "Rules": "No data", "Total_Hand": "No data", "Sportsbook": "No data", "State_Taxe": "No data" }, "geometry": { "type": "Point", "coordinates": [ -119.60237, 37.24226 ] } },
{ "type": "Feature", "properties": { "Name": "Connecticut", "Status": "Failed legislation in 2020", "Wagers": "No data", "Casinos": "No data", "Rules": "No data", "Total_Hand": "No data", "Sportsbook": "No data", "State_Taxe": "No data" }, "geometry": { "type": "Point", "coordinates": [ -72.72549, 41.62694 ] } },
{ "type": "Feature", "properties": { "Name": "Florida", "Status": "Failed legislation in 2020", "Wagers": "No data", "Casinos": "No data", "Rules": "No data", "Total_Hand": "No data", "Sportsbook": "No data", "State_Taxe": "No data" }, "geometry": { "type": "Point", "coordinates": [ -82.49361, 28.65786 ] } },
{ "type": "Feature", "properties": { "Name": "Georgia", "Status": "Failed legislation in 2020", "Wagers": "No data", "Casinos": "No data", "Rules": "No data", "Total_Hand": "No data", "Sportsbook": "No data", "State_Taxe": "No data" }, "geometry": { "type": "Point", "coordinates": [ -83.4566, 32.65901 ] } },
{ "type": "Feature", "properties": { "Name": "Idaho", "Status": "No legislation in 2020", "Wagers": "No data", "Casinos": "No data", "Rules": "No data", "Total_Hand": "No data", "Sportsbook": "No data", "State_Taxe": "No data" }, "geometry": { "type": "Point", "coordinates": [ -114.65183, 44.39271 ] } },
{ "type": "Feature", "properties": { "Name": "Kentucky", "Status": "Failed legislation in 2020", "Wagers": "No data", "Casinos": "No data", "Rules": "No data", "Total_Hand": "No data", "Sportsbook": "No data", "State_Taxe": "No data" }, "geometry": { "type": "Point", "coordinates": [ -85.28618, 37.53157 ] } },
{ "type": "Feature", "properties": { "Name": "Maine", "Status": "Failed legislation in 2020", "Wagers": "No data", "Casinos": "No data", "Rules": "No data", "Total_Hand": "No data", "Sportsbook": "No data", "State_Taxe": "No data" }, "geometry": { "type": "Point", "coordinates": [ -69.23966, 45.40022 ] } },
{ "type": "Feature", "properties": { "Name": "Minnesota", "Status": "Failed legislation in 2020", "Wagers": "No data", "Casinos": "No data", "Rules": "No data", "Total_Hand": "No data", "Sportsbook": "No data", "State_Taxe": "No data" }, "geometry": { "type": "Point", "coordinates": [ -94.19758, 46.34392 ] } },
{ "type": "Feature", "properties": { "Name": "Missouri", "Status": "Failed legislation in 2020", "Wagers": "No data", "Casinos": "No data", "Rules": "No data", "Total_Hand": "No data", "Sportsbook": "No data", "State_Taxe": "No data" }, "geometry": { "type": "Point", "coordinates": [ -92.49201, 38.38417 ] } },
{ "type": "Feature", "properties": { "Name": "North Dakota", "Status": "No legislation in 2020", "Wagers": "No data", "Casinos": "No data", "Rules": "No data", "Total_Hand": "No data", "Sportsbook": "No data", "State_Taxe": "No data" }, "geometry": { "type": "Point", "coordinates": [ -100.45974, 47.4449 ] } },
{ "type": "Feature", "properties": { "Name": "Oklahoma", "Status": "No legislation in 2020", "Wagers": "No data", "Casinos": "No data", "Rules": "No data", "Total_Hand": "No data", "Sportsbook": "No data", "State_Taxe": "No data" }, "geometry": { "type": "Point", "coordinates": [ -97.51155, 35.58952 ] } },
{ "type": "Feature", "properties": { "Name": "South Carolina", "Status": "No legislation in 2020", "Wagers": "No data", "Casinos": "No data", "Rules": "No data", "Total_Hand": "No data", "Sportsbook": "No data", "State_Taxe": "No data" }, "geometry": { "type": "Point", "coordinates": [ -80.90027, 33.9194 ] } },
{ "type": "Feature", "properties": { "Name": "Texas", "Status": "No legislation in 2020", "Wagers": "No data", "Casinos": "No data", "Rules": "No data", "Total_Hand": "No data", "Sportsbook": "No data", "State_Taxe": "No data" }, "geometry": { "type": "Point", "coordinates": [ -99.35325, 31.49914 ] } },
{ "type": "Feature", "properties": { "Name": "Utah", "Status": "No legislation in 2020", "Wagers": "No data", "Casinos": "No data", "Rules": "No data", "Total_Hand": "No data", "Sportsbook": "No data", "State_Taxe": "No data" }, "geometry": { "type": "Point", "coordinates": [ -111.67421, 39.32751 ] } },
{ "type": "Feature", "properties": { "Name": "Wisconsin", "Status": "No legislation in 2020", "Wagers": "No data", "Casinos": "No data", "Rules": "No data", "Total_Hand": "No data", "Sportsbook": "No data", "State_Taxe": "No data" }, "geometry": { "type": "Point", "coordinates": [ -89.73709, 44.64597 ] } },
{ "type": "Feature", "properties": { "Name": "Wyoming", "Status": "Failed legislation in 2020", "Wagers": "No data", "Casinos": "No data", "Rules": "No data", "Total_Hand": "No data", "Sportsbook": "No data", "State_Taxe": "No data" }, "geometry": { "type": "Point", "coordinates": [ -107.53992, 43.00031 ] } }
]
}
